name: github release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for ncipollo/release-action to create a release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0

    - name: Setup jdk-17
      uses: actions/setup-java@ea15b3b99cdc9ac45af1882d085e3f9297a75a8b # main
      with:
        java-version: 17
        distribution: 'adopt'

  # NYI ebnf is not generated because of missing antlr/pcregrep
    - name: build release
      run: make release

    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat version.txt)"

    - uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1.12.0
      with:
        artifacts: "fuzion_${{ steps.getversion.outputs.version }}.tar.gz"
        tag: "v${{ steps.getversion.outputs.version }}"
        prerelease: false
        generateReleaseNotes: false
        token: ${{ secrets.GITHUB_TOKEN }}
